"""PostgreSQL integration tests for the migration chain and its drift."""

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect, text
from sqlalchemy.engine import make_url

from database_fixtures import (
    check_migrations,
    create_database,
    drop_database,
    migrate,
    migration_config,
    migration_environment,
    worker_database_url,
)


def baseline_revision(config: Config) -> str:
    """Return the root revision identifier, which new revisions may follow."""
    scripts = ScriptDirectory.from_config(config)
    for revision in scripts.walk_revisions():
        if revision.down_revision is None:
            return revision.revision
    raise AssertionError("the migration chain has no baseline revision")


def stored_revision(engine_url: str) -> str | None:
    """Read the revision the database is currently at."""
    engine = create_engine(engine_url)
    try:
        with engine.connect() as connection:
            return connection.scalar(text("SELECT version_num FROM alembic_version"))
    finally:
        engine.dispose()


def table_names(engine_url: str) -> set[str]:
    """Read the table names the database currently holds."""
    engine = create_engine(engine_url)
    try:
        with engine.connect() as connection:
            return set(inspect(connection).get_table_names())
    finally:
        engine.dispose()


@pytest.mark.integration
def test_baseline_can_upgrade_downgrade_and_upgrade_again(
    migrated_database: str,
) -> None:
    url = make_url(migrated_database)
    config = migration_config()
    baseline_id = baseline_revision(config)

    with migration_environment(url):
        command.downgrade(config, "base")
    assert table_names(migrated_database) == {"alembic_version"}
    assert stored_revision(migrated_database) is None

    with migration_environment(url):
        command.upgrade(config, baseline_id)
    assert table_names(migrated_database) == {"alembic_version"}
    assert stored_revision(migrated_database) == baseline_id

    with migration_environment(url):
        command.downgrade(config, "base")
    assert stored_revision(migrated_database) is None

    with migration_environment(url):
        command.upgrade(config, baseline_id)
    assert stored_revision(migrated_database) == baseline_id


@pytest.mark.integration
def test_the_migrated_schema_matches_the_declared_tables(
    migrated_database: str,
) -> None:
    """Every revision applied leaves behind the schema the code declares."""
    check_migrations(make_url(migrated_database))


@pytest.mark.integration
def test_a_column_missing_from_the_database_is_reported(
    migrated_database: str,
) -> None:
    """Prove the drift check can fail, on a database of its own."""
    drift_url = worker_database_url(make_url(migrated_database), "drift")
    create_database(drift_url)
    try:
        migrate(drift_url)
        engine = create_engine(drift_url)
        try:
            with engine.begin() as connection:
                connection.execute(text("ALTER TABLE jobs DROP COLUMN last_error_code"))
        finally:
            engine.dispose()

        with pytest.raises(AutogenerateDiffsDetected):
            check_migrations(drift_url)
    finally:
        drop_database(drift_url)
